services:
  db:
    image: postgres:16-alpine
    container_name: gastos_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gastos
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d gastos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
