"""Translate schema to english

Revision ID: 03907144cac0
Revises: d32ec49642d2
Create Date: 2026-04-13 14:24:04.801311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03907144cac0'
down_revision: Union[str, None] = 'd32ec49642d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('jan', sa.Float(), nullable=True),
    sa.Column('feb', sa.Float(), nullable=True),
    sa.Column('mar', sa.Float(), nullable=True),
    sa.Column('apr', sa.Float(), nullable=True),
    sa.Column('may', sa.Float(), nullable=True),
    sa.Column('jun', sa.Float(), nullable=True),
    sa.Column('jul', sa.Float(), nullable=True),
    sa.Column('aug', sa.Float(), nullable=True),
    sa.Column('sep', sa.Float(), nullable=True),
    sa.Column('oct', sa.Float(), nullable=True),
    sa.Column('nov', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.Column('actual_jan', sa.Float(), nullable=True),
    sa.Column('actual_feb', sa.Float(), nullable=True),
    sa.Column('actual_mar', sa.Float(), nullable=True),
    sa.Column('actual_apr', sa.Float(), nullable=True),
    sa.Column('actual_may', sa.Float(), nullable=True),
    sa.Column('actual_jun', sa.Float(), nullable=True),
    sa.Column('actual_jul', sa.Float(), nullable=True),
    sa.Column('actual_aug', sa.Float(), nullable=True),
    sa.Column('actual_sep', sa.Float(), nullable=True),
    sa.Column('actual_oct', sa.Float(), nullable=True),
    sa.Column('actual_nov', sa.Float(), nullable=True),
    sa.Column('actual_dec', sa.Float(), nullable=True),
    sa.Column('actual_card_jan', sa.Float(), nullable=True),
    sa.Column('actual_card_feb', sa.Float(), nullable=True),
    sa.Column('actual_card_mar', sa.Float(), nullable=True),
    sa.Column('actual_card_apr', sa.Float(), nullable=True),
    sa.Column('actual_card_may', sa.Float(), nullable=True),
    sa.Column('actual_card_jun', sa.Float(), nullable=True),
    sa.Column('actual_card_jul', sa.Float(), nullable=True),
    sa.Column('actual_card_aug', sa.Float(), nullable=True),
    sa.Column('actual_card_sep', sa.Float(), nullable=True),
    sa.Column('actual_card_oct', sa.Float(), nullable=True),
    sa.Column('actual_card_nov', sa.Float(), nullable=True),
    sa.Column('actual_card_dec', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['taxonomy_sections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year', 'section_id', 'description', name='uix_tenant_year_section_description')
    )
    op.create_index(op.f('ix_expense_details_id'), 'expense_details', ['id'], unique=False)
    op.create_index(op.f('ix_expense_details_section_id'), 'expense_details', ['section_id'], unique=False)
    op.create_index(op.f('ix_expense_details_tenant_id'), 'expense_details', ['tenant_id'], unique=False)
    op.create_table('revenues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('jan', sa.Float(), nullable=True),
    sa.Column('feb', sa.Float(), nullable=True),
    sa.Column('mar', sa.Float(), nullable=True),
    sa.Column('apr', sa.Float(), nullable=True),
    sa.Column('may', sa.Float(), nullable=True),
    sa.Column('jun', sa.Float(), nullable=True),
    sa.Column('jul', sa.Float(), nullable=True),
    sa.Column('aug', sa.Float(), nullable=True),
    sa.Column('sep', sa.Float(), nullable=True),
    sa.Column('oct', sa.Float(), nullable=True),
    sa.Column('nov', sa.Float(), nullable=True),
    sa.Column('dec', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenues_id'), 'revenues', ['id'], unique=False)
    op.create_index(op.f('ix_revenues_tenant_id'), 'revenues', ['tenant_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('actual_spending', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month', 'category_id', name='uix_tenant_month_category')
    )
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_table('card_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_limit', sa.Float(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('alert_pct', sa.Integer(), nullable=True),
    sa.Column('closing_day', sa.Integer(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_configs_id'), 'card_configs', ['id'], unique=False)
    op.create_index(op.f('ix_card_configs_tenant_id'), 'card_configs', ['tenant_id'], unique=False)
    op.create_table('inventory_block_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('prev_month_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_block_a_category_id'), 'inventory_block_a', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_block_a_channel_id'), 'inventory_block_a', ['channel_id'], unique=False)
    op.create_index(op.f('ix_inventory_block_a_id'), 'inventory_block_a', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_block_a_tenant_id'), 'inventory_block_a', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_block_a_unit_id'), 'inventory_block_a', ['unit_id'], unique=False)
    op.create_table('inventory_block_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('prev_month_price', sa.Float(), nullable=True),
    sa.Column('price_delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_block_b_category_id'), 'inventory_block_b', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_block_b_channel_id'), 'inventory_block_b', ['channel_id'], unique=False)
    op.create_index(op.f('ix_inventory_block_b_id'), 'inventory_block_b', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_block_b_tenant_id'), 'inventory_block_b', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_block_b_unit_id'), 'inventory_block_b', ['unit_id'], unique=False)
    op.drop_index('ix_config_tarjeta_id', table_name='config_tarjeta')
    op.drop_index('ix_config_tarjeta_tenant_id', table_name='config_tarjeta')
    op.drop_table('config_tarjeta')
    op.drop_index('ix_ingresos_id', table_name='ingresos')
    op.drop_index('ix_ingresos_tenant_id', table_name='ingresos')
    op.drop_table('ingresos')
    op.drop_index('ix_gastos_detalle_id', table_name='gastos_detalle')
    op.drop_index('ix_gastos_detalle_section_id', table_name='gastos_detalle')
    op.drop_index('ix_gastos_detalle_tenant_id', table_name='gastos_detalle')
    op.drop_table('gastos_detalle')
    op.drop_index('ix_presupuesto_category_id', table_name='presupuesto')
    op.drop_index('ix_presupuesto_id', table_name='presupuesto')
    op.drop_index('ix_presupuesto_tenant_id', table_name='presupuesto')
    op.drop_table('presupuesto')
    op.drop_index('ix_bloque_b_category_id', table_name='bloque_b')
    op.drop_index('ix_bloque_b_channel_id', table_name='bloque_b')
    op.drop_index('ix_bloque_b_id', table_name='bloque_b')
    op.drop_index('ix_bloque_b_tenant_id', table_name='bloque_b')
    op.drop_index('ix_bloque_b_unit_id', table_name='bloque_b')
    op.drop_table('bloque_b')
    op.drop_index('ix_bloque_a_category_id', table_name='bloque_a')
    op.drop_index('ix_bloque_a_channel_id', table_name='bloque_a')
    op.drop_index('ix_bloque_a_id', table_name='bloque_a')
    op.drop_index('ix_bloque_a_tenant_id', table_name='bloque_a')
    op.drop_index('ix_bloque_a_unit_id', table_name='bloque_a')
    op.drop_table('bloque_a')
    op.add_column('items', sa.Column('month', sa.String(), nullable=False))
    op.add_column('items', sa.Column('date', sa.String(), nullable=True))
    op.add_column('items', sa.Column('name', sa.String(), nullable=False))
    op.add_column('items', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('prev_month_price', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('items', sa.Column('source', sa.String(), nullable=True))
    op.drop_index('ix_items_fuente', table_name='items')
    op.create_index(op.f('ix_items_source'), 'items', ['source'], unique=False)
    op.drop_column('items', 'nombre')
    op.drop_column('items', 'fuente')
    op.drop_column('items', 'precio_unit')
    op.drop_column('items', 'fecha')
    op.drop_column('items', 'cantidad')
    op.drop_column('items', 'precio_mes_ant')
    op.drop_column('items', 'mes')
    op.drop_column('items', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('mes', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('precio_mes_ant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('fecha', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('precio_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('fuente', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_items_source'), table_name='items')
    op.create_index('ix_items_fuente', 'items', ['fuente'], unique=False)
    op.drop_column('items', 'source')
    op.drop_column('items', 'status')
    op.drop_column('items', 'prev_month_price')
    op.drop_column('items', 'unit_price')
    op.drop_column('items', 'quantity')
    op.drop_column('items', 'name')
    op.drop_column('items', 'date')
    op.drop_column('items', 'month')
    op.create_table('bloque_a',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_mes_ant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], name='bloque_a_category_id_fkey'),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], name='bloque_a_channel_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='bloque_a_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], name='bloque_a_unit_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bloque_a_pkey')
    )
    op.create_index('ix_bloque_a_unit_id', 'bloque_a', ['unit_id'], unique=False)
    op.create_index('ix_bloque_a_tenant_id', 'bloque_a', ['tenant_id'], unique=False)
    op.create_index('ix_bloque_a_id', 'bloque_a', ['id'], unique=False)
    op.create_index('ix_bloque_a_channel_id', 'bloque_a', ['channel_id'], unique=False)
    op.create_index('ix_bloque_a_category_id', 'bloque_a', ['category_id'], unique=False)
    op.create_table('bloque_b',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precio_mes_ant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delta_precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], name='bloque_b_category_id_fkey'),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], name='bloque_b_channel_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='bloque_b_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], name='bloque_b_unit_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bloque_b_pkey')
    )
    op.create_index('ix_bloque_b_unit_id', 'bloque_b', ['unit_id'], unique=False)
    op.create_index('ix_bloque_b_tenant_id', 'bloque_b', ['tenant_id'], unique=False)
    op.create_index('ix_bloque_b_id', 'bloque_b', ['id'], unique=False)
    op.create_index('ix_bloque_b_channel_id', 'bloque_b', ['channel_id'], unique=False)
    op.create_index('ix_bloque_b_category_id', 'bloque_b', ['category_id'], unique=False)
    op.create_table('presupuesto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mes', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('presupuesto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gasto_real', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], name='presupuesto_category_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='presupuesto_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='presupuesto_pkey'),
    sa.UniqueConstraint('tenant_id', 'mes', 'category_id', name='uix_tenant_mes_category', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_presupuesto_tenant_id', 'presupuesto', ['tenant_id'], unique=False)
    op.create_index('ix_presupuesto_id', 'presupuesto', ['id'], unique=False)
    op.create_index('ix_presupuesto_category_id', 'presupuesto', ['category_id'], unique=False)
    op.create_table('gastos_detalle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('concepto', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ene', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('abr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('may', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jun', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jul', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ago', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nov', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_ene', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_feb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_mar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_abr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_may', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_jun', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_jul', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_ago', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_sep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_oct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_nov', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_dic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_ene', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_feb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_mar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_abr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_may', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_jun', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_jul', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_ago', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_sep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_oct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_nov', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('real_tc_dic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['taxonomy_sections.id'], name='gastos_detalle_section_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='gastos_detalle_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gastos_detalle_pkey'),
    sa.UniqueConstraint('tenant_id', 'anio', 'section_id', 'concepto', name='uix_tenant_anio_section_concepto', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_gastos_detalle_tenant_id', 'gastos_detalle', ['tenant_id'], unique=False)
    op.create_index('ix_gastos_detalle_section_id', 'gastos_detalle', ['section_id'], unique=False)
    op.create_index('ix_gastos_detalle_id', 'gastos_detalle', ['id'], unique=False)
    op.create_table('ingresos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fuente', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ene', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('abr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('may', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jun', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('jul', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ago', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('oct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nov', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='ingresos_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingresos_pkey')
    )
    op.create_index('ix_ingresos_tenant_id', 'ingresos', ['tenant_id'], unique=False)
    op.create_index('ix_ingresos_id', 'ingresos', ['id'], unique=False)
    op.create_table('config_tarjeta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cupo_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alerta_pct', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dia_corte', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dia_pago', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], name='config_tarjeta_channel_id_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='config_tarjeta_tenant_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='config_tarjeta_pkey')
    )
    op.create_index('ix_config_tarjeta_tenant_id', 'config_tarjeta', ['tenant_id'], unique=False)
    op.create_index('ix_config_tarjeta_id', 'config_tarjeta', ['id'], unique=False)
    op.drop_index(op.f('ix_inventory_block_b_unit_id'), table_name='inventory_block_b')
    op.drop_index(op.f('ix_inventory_block_b_tenant_id'), table_name='inventory_block_b')
    op.drop_index(op.f('ix_inventory_block_b_id'), table_name='inventory_block_b')
    op.drop_index(op.f('ix_inventory_block_b_channel_id'), table_name='inventory_block_b')
    op.drop_index(op.f('ix_inventory_block_b_category_id'), table_name='inventory_block_b')
    op.drop_table('inventory_block_b')
    op.drop_index(op.f('ix_inventory_block_a_unit_id'), table_name='inventory_block_a')
    op.drop_index(op.f('ix_inventory_block_a_tenant_id'), table_name='inventory_block_a')
    op.drop_index(op.f('ix_inventory_block_a_id'), table_name='inventory_block_a')
    op.drop_index(op.f('ix_inventory_block_a_channel_id'), table_name='inventory_block_a')
    op.drop_index(op.f('ix_inventory_block_a_category_id'), table_name='inventory_block_a')
    op.drop_table('inventory_block_a')
    op.drop_index(op.f('ix_card_configs_tenant_id'), table_name='card_configs')
    op.drop_index(op.f('ix_card_configs_id'), table_name='card_configs')
    op.drop_table('card_configs')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_revenues_tenant_id'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_id'), table_name='revenues')
    op.drop_table('revenues')
    op.drop_index(op.f('ix_expense_details_tenant_id'), table_name='expense_details')
    op.drop_index(op.f('ix_expense_details_section_id'), table_name='expense_details')
    op.drop_index(op.f('ix_expense_details_id'), table_name='expense_details')
    op.drop_table('expense_details')
    # ### end Alembic commands ###
