"""Add tenant_id to taxonomy sections

Revision ID: 1028335c6f62
Revises: fd85a011d566
Create Date: 2026-04-15 09:03:09.930077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1028335c6f62'
down_revision: Union[str, None] = 'fd85a011d566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxonomy_sections', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.drop_constraint('taxonomy_sections_name_key', 'taxonomy_sections', type_='unique')
    op.create_index(op.f('ix_taxonomy_sections_tenant_id'), 'taxonomy_sections', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'taxonomy_sections', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taxonomy_sections', type_='foreignkey')
    op.drop_index(op.f('ix_taxonomy_sections_tenant_id'), table_name='taxonomy_sections')
    op.create_unique_constraint('taxonomy_sections_name_key', 'taxonomy_sections', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('taxonomy_sections', 'tenant_id')
    # ### end Alembic commands ###
