"""Add sqlite triggers and health logs

Revision ID: 25703f6230ea
Revises: 502e48cd7883
Create Date: 2026-04-17 20:19:41.743488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25703f6230ea'
down_revision: Union[str, None] = '502e48cd7883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('affected_records', sa.Integer(), nullable=True),
    sa.Column('before_state_json', sa.String(), nullable=True),
    sa.Column('after_state_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_snapshots_id'), 'reconciliation_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_snapshots_tenant_id'), 'reconciliation_snapshots', ['tenant_id'], unique=False)
    op.create_table('system_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('duplicate_clusters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_logs_id'), 'system_health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_health_logs_tenant_id'), 'system_health_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION check_is_automatic_immutable()
    RETURNS trigger AS $$
    BEGIN
        IF OLD.is_automatic = true AND NEW.is_automatic = false THEN
            RAISE EXCEPTION 'Architectural Invariant Violation: Cannot unset is_automatic via DB';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    
    CREATE TRIGGER trg_check_is_automatic_update
    BEFORE UPDATE ON expense_details
    FOR EACH ROW EXECUTE FUNCTION check_is_automatic_immutable();
    
    CREATE OR REPLACE FUNCTION check_is_automatic_delete()
    RETURNS trigger AS $$
    BEGIN
        IF OLD.is_automatic = true THEN
            RAISE EXCEPTION 'Architectural Invariant Violation: Cannot delete system record via DB';
        END IF;
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    
    CREATE TRIGGER trg_check_is_automatic_delete
    BEFORE DELETE ON expense_details
    FOR EACH ROW EXECUTE FUNCTION check_is_automatic_delete();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_check_is_automatic_update ON expense_details")
    op.execute("DROP FUNCTION IF EXISTS check_is_automatic_immutable")
    op.execute("DROP TRIGGER IF EXISTS trg_check_is_automatic_delete ON expense_details")
    op.execute("DROP FUNCTION IF EXISTS check_is_automatic_delete")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_health_logs_tenant_id'), table_name='system_health_logs')
    op.drop_index(op.f('ix_system_health_logs_id'), table_name='system_health_logs')
    op.drop_table('system_health_logs')
    op.drop_index(op.f('ix_reconciliation_snapshots_tenant_id'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_id'), table_name='reconciliation_snapshots')
    op.drop_table('reconciliation_snapshots')
    # ### end Alembic commands ###
