"""add multi tenant support

Revision ID: 33481b3c2df6
Revises: 544ddb85ba9f
Create Date: 2026-04-16 16:26:11.002324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33481b3c2df6'
down_revision: Union[str, None] = '544ddb85ba9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_access_id'), 'tenant_access', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_access_tenant_id'), 'tenant_access', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_access_user_id'), 'tenant_access', ['user_id'], unique=False)
    op.add_column('tenants', sa.Column('invite_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['invite_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'invite_code')
    op.drop_index(op.f('ix_tenant_access_user_id'), table_name='tenant_access')
    op.drop_index(op.f('ix_tenant_access_tenant_id'), table_name='tenant_access')
    op.drop_index(op.f('ix_tenant_access_id'), table_name='tenant_access')
    op.drop_table('tenant_access')
    # ### end Alembic commands ###
