"""add_unique_constraint_card_monthly_state

Revision ID: 544ddb85ba9f
Revises: a6b9d0a65ee0
Create Date: 2026-04-16 14:32:38.625166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544ddb85ba9f'
down_revision: Union[str, None] = 'a6b9d0a65ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_card_monthly_state', 'card_monthly_states', ['tenant_id', 'month'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_card_monthly_state', 'card_monthly_states', type_='unique')
    # ### end Alembic commands ###
