"""optimistic locking and snapshot indexing

Revision ID: 5b717d77cea7
Revises: 99b4e25dcf81
Create Date: 2026-04-17 22:49:16.028057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b717d77cea7'
down_revision: Union[str, None] = '99b4e25dcf81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_details', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('items', sa.Column('version_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('reconciliation_snapshots', sa.Column('affected_records_ids', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reconciliation_snapshots', 'affected_records_ids')
    op.drop_column('items', 'version_id')
    op.drop_column('expense_details', 'version_id')
    # ### end Alembic commands ###
