"""Add card monthly state

Revision ID: a6b9d0a65ee0
Revises: 1028335c6f62
Create Date: 2026-04-16 12:46:07.747195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b9d0a65ee0'
down_revision: Union[str, None] = '1028335c6f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_monthly_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('manual_payment', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_monthly_states_id'), 'card_monthly_states', ['id'], unique=False)
    op.create_index(op.f('ix_card_monthly_states_month'), 'card_monthly_states', ['month'], unique=False)
    op.create_index(op.f('ix_card_monthly_states_tenant_id'), 'card_monthly_states', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_monthly_states_tenant_id'), table_name='card_monthly_states')
    op.drop_index(op.f('ix_card_monthly_states_month'), table_name='card_monthly_states')
    op.drop_index(op.f('ix_card_monthly_states_id'), table_name='card_monthly_states')
    op.drop_table('card_monthly_states')
    # ### end Alembic commands ###
