"""add category_id to expense_detail

Revision ID: c584bba29385
Revises: 33481b3c2df6
Create Date: 2026-04-17 11:39:26.858054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c584bba29385'
down_revision: Union[str, None] = '33481b3c2df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_details', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expense_details_category_id'), 'expense_details', ['category_id'], unique=False)
    op.create_foreign_key(None, 'expense_details', 'taxonomy_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense_details', type_='foreignkey')
    op.drop_index(op.f('ix_expense_details_category_id'), table_name='expense_details')
    op.drop_column('expense_details', 'category_id')
    # ### end Alembic commands ###
