"""Initial normalized schema for production

Revision ID: d32ec49642d2
Revises: 
Create Date: 2026-04-13 13:04:54.818998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32ec49642d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('color_bg', sa.String(), nullable=True),
    sa.Column('color_accent', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_taxonomy_sections_id'), 'taxonomy_sections', ['id'], unique=False)
    op.create_table('taxonomy_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_taxonomy_units_id'), 'taxonomy_units', ['id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('gastos_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('ene', sa.Float(), nullable=True),
    sa.Column('feb', sa.Float(), nullable=True),
    sa.Column('mar', sa.Float(), nullable=True),
    sa.Column('abr', sa.Float(), nullable=True),
    sa.Column('may', sa.Float(), nullable=True),
    sa.Column('jun', sa.Float(), nullable=True),
    sa.Column('jul', sa.Float(), nullable=True),
    sa.Column('ago', sa.Float(), nullable=True),
    sa.Column('sep', sa.Float(), nullable=True),
    sa.Column('oct', sa.Float(), nullable=True),
    sa.Column('nov', sa.Float(), nullable=True),
    sa.Column('dic', sa.Float(), nullable=True),
    sa.Column('real_ene', sa.Float(), nullable=True),
    sa.Column('real_feb', sa.Float(), nullable=True),
    sa.Column('real_mar', sa.Float(), nullable=True),
    sa.Column('real_abr', sa.Float(), nullable=True),
    sa.Column('real_may', sa.Float(), nullable=True),
    sa.Column('real_jun', sa.Float(), nullable=True),
    sa.Column('real_jul', sa.Float(), nullable=True),
    sa.Column('real_ago', sa.Float(), nullable=True),
    sa.Column('real_sep', sa.Float(), nullable=True),
    sa.Column('real_oct', sa.Float(), nullable=True),
    sa.Column('real_nov', sa.Float(), nullable=True),
    sa.Column('real_dic', sa.Float(), nullable=True),
    sa.Column('real_tc_ene', sa.Float(), nullable=True),
    sa.Column('real_tc_feb', sa.Float(), nullable=True),
    sa.Column('real_tc_mar', sa.Float(), nullable=True),
    sa.Column('real_tc_abr', sa.Float(), nullable=True),
    sa.Column('real_tc_may', sa.Float(), nullable=True),
    sa.Column('real_tc_jun', sa.Float(), nullable=True),
    sa.Column('real_tc_jul', sa.Float(), nullable=True),
    sa.Column('real_tc_ago', sa.Float(), nullable=True),
    sa.Column('real_tc_sep', sa.Float(), nullable=True),
    sa.Column('real_tc_oct', sa.Float(), nullable=True),
    sa.Column('real_tc_nov', sa.Float(), nullable=True),
    sa.Column('real_tc_dic', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['taxonomy_sections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'anio', 'section_id', 'concepto', name='uix_tenant_anio_section_concepto')
    )
    op.create_index(op.f('ix_gastos_detalle_id'), 'gastos_detalle', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_detalle_section_id'), 'gastos_detalle', ['section_id'], unique=False)
    op.create_index(op.f('ix_gastos_detalle_tenant_id'), 'gastos_detalle', ['tenant_id'], unique=False)
    op.create_table('ingresos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('ene', sa.Float(), nullable=True),
    sa.Column('feb', sa.Float(), nullable=True),
    sa.Column('mar', sa.Float(), nullable=True),
    sa.Column('abr', sa.Float(), nullable=True),
    sa.Column('may', sa.Float(), nullable=True),
    sa.Column('jun', sa.Float(), nullable=True),
    sa.Column('jul', sa.Float(), nullable=True),
    sa.Column('ago', sa.Float(), nullable=True),
    sa.Column('sep', sa.Float(), nullable=True),
    sa.Column('oct', sa.Float(), nullable=True),
    sa.Column('nov', sa.Float(), nullable=True),
    sa.Column('dic', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingresos_id'), 'ingresos', ['id'], unique=False)
    op.create_index(op.f('ix_ingresos_tenant_id'), 'ingresos', ['tenant_id'], unique=False)
    op.create_table('taxonomy_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['taxonomy_sections.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_categories_id'), 'taxonomy_categories', ['id'], unique=False)
    op.create_index(op.f('ix_taxonomy_categories_section_id'), 'taxonomy_categories', ['section_id'], unique=False)
    op.create_index(op.f('ix_taxonomy_categories_tenant_id'), 'taxonomy_categories', ['tenant_id'], unique=False)
    op.create_table('taxonomy_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_channels_id'), 'taxonomy_channels', ['id'], unique=False)
    op.create_index(op.f('ix_taxonomy_channels_tenant_id'), 'taxonomy_channels', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('bloque_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unit', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('precio_mes_ant', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloque_a_category_id'), 'bloque_a', ['category_id'], unique=False)
    op.create_index(op.f('ix_bloque_a_channel_id'), 'bloque_a', ['channel_id'], unique=False)
    op.create_index(op.f('ix_bloque_a_id'), 'bloque_a', ['id'], unique=False)
    op.create_index(op.f('ix_bloque_a_tenant_id'), 'bloque_a', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bloque_a_unit_id'), 'bloque_a', ['unit_id'], unique=False)
    op.create_table('bloque_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('precio_kg', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('precio_mes_ant', sa.Float(), nullable=True),
    sa.Column('delta_precio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloque_b_category_id'), 'bloque_b', ['category_id'], unique=False)
    op.create_index(op.f('ix_bloque_b_channel_id'), 'bloque_b', ['channel_id'], unique=False)
    op.create_index(op.f('ix_bloque_b_id'), 'bloque_b', ['id'], unique=False)
    op.create_index(op.f('ix_bloque_b_tenant_id'), 'bloque_b', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bloque_b_unit_id'), 'bloque_b', ['unit_id'], unique=False)
    op.create_table('config_tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cupo_total', sa.Float(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('alerta_pct', sa.Integer(), nullable=True),
    sa.Column('dia_corte', sa.Integer(), nullable=True),
    sa.Column('dia_pago', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_tarjeta_id'), 'config_tarjeta', ['id'], unique=False)
    op.create_index(op.f('ix_config_tarjeta_tenant_id'), 'config_tarjeta', ['tenant_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unit', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('precio_mes_ant', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['taxonomy_channels.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['taxonomy_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_channel_id'), 'items', ['channel_id'], unique=False)
    op.create_index(op.f('ix_items_fuente'), 'items', ['fuente'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_tenant_id'), 'items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_items_unit_id'), 'items', ['unit_id'], unique=False)
    op.create_table('presupuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('presupuesto', sa.Float(), nullable=True),
    sa.Column('gasto_real', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['taxonomy_categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'mes', 'category_id', name='uix_tenant_mes_category')
    )
    op.create_index(op.f('ix_presupuesto_category_id'), 'presupuesto', ['category_id'], unique=False)
    op.create_index(op.f('ix_presupuesto_id'), 'presupuesto', ['id'], unique=False)
    op.create_index(op.f('ix_presupuesto_tenant_id'), 'presupuesto', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presupuesto_tenant_id'), table_name='presupuesto')
    op.drop_index(op.f('ix_presupuesto_id'), table_name='presupuesto')
    op.drop_index(op.f('ix_presupuesto_category_id'), table_name='presupuesto')
    op.drop_table('presupuesto')
    op.drop_index(op.f('ix_items_unit_id'), table_name='items')
    op.drop_index(op.f('ix_items_tenant_id'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_fuente'), table_name='items')
    op.drop_index(op.f('ix_items_channel_id'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_config_tarjeta_tenant_id'), table_name='config_tarjeta')
    op.drop_index(op.f('ix_config_tarjeta_id'), table_name='config_tarjeta')
    op.drop_table('config_tarjeta')
    op.drop_index(op.f('ix_bloque_b_unit_id'), table_name='bloque_b')
    op.drop_index(op.f('ix_bloque_b_tenant_id'), table_name='bloque_b')
    op.drop_index(op.f('ix_bloque_b_id'), table_name='bloque_b')
    op.drop_index(op.f('ix_bloque_b_channel_id'), table_name='bloque_b')
    op.drop_index(op.f('ix_bloque_b_category_id'), table_name='bloque_b')
    op.drop_table('bloque_b')
    op.drop_index(op.f('ix_bloque_a_unit_id'), table_name='bloque_a')
    op.drop_index(op.f('ix_bloque_a_tenant_id'), table_name='bloque_a')
    op.drop_index(op.f('ix_bloque_a_id'), table_name='bloque_a')
    op.drop_index(op.f('ix_bloque_a_channel_id'), table_name='bloque_a')
    op.drop_index(op.f('ix_bloque_a_category_id'), table_name='bloque_a')
    op.drop_table('bloque_a')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_taxonomy_channels_tenant_id'), table_name='taxonomy_channels')
    op.drop_index(op.f('ix_taxonomy_channels_id'), table_name='taxonomy_channels')
    op.drop_table('taxonomy_channels')
    op.drop_index(op.f('ix_taxonomy_categories_tenant_id'), table_name='taxonomy_categories')
    op.drop_index(op.f('ix_taxonomy_categories_section_id'), table_name='taxonomy_categories')
    op.drop_index(op.f('ix_taxonomy_categories_id'), table_name='taxonomy_categories')
    op.drop_table('taxonomy_categories')
    op.drop_index(op.f('ix_ingresos_tenant_id'), table_name='ingresos')
    op.drop_index(op.f('ix_ingresos_id'), table_name='ingresos')
    op.drop_table('ingresos')
    op.drop_index(op.f('ix_gastos_detalle_tenant_id'), table_name='gastos_detalle')
    op.drop_index(op.f('ix_gastos_detalle_section_id'), table_name='gastos_detalle')
    op.drop_index(op.f('ix_gastos_detalle_id'), table_name='gastos_detalle')
    op.drop_table('gastos_detalle')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_taxonomy_units_id'), table_name='taxonomy_units')
    op.drop_table('taxonomy_units')
    op.drop_index(op.f('ix_taxonomy_sections_id'), table_name='taxonomy_sections')
    op.drop_table('taxonomy_sections')
    # ### end Alembic commands ###
