"""Add payment_method to items

Revision ID: fd85a011d566
Revises: 03907144cac0
Create Date: 2026-04-14 17:00:40.669154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd85a011d566'
down_revision: Union[str, None] = '03907144cac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'payment_method')
    # ### end Alembic commands ###
